import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarDesktop from "@/Components/NavBarDesktop";

// app/layout.tsx or app/layout.js
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Add the weights you need
  variable: '--font-poppins', // Optional: to use with Tailwind custom variable
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body
        className={` ${poppins.className}  antialiased`}
      >
        
        {children}
      </body>
    </html>
  );
}
